### PR TITLE
now the cloud can be resized

### PR DESCRIPTION
**Pull request by szydan**
Hi this pull request is to allow for dynamic width and height parameters.
See demo page - now you can change the container dimensions and jqcloud will refresh

### CODE REVIEW

**Comment by mistic100** [comment]
You don't need to destroy and rebuild.
jQCloud already has a dynamic size mode http://mistic100.github.io/jQCloud/demo.html#autosize
Try to use it.

**Comment by szydan** [comment]
Hi thanks for the hint

**Comment by owaaa** [comment]
autoResize=true didn't work for me. I had to modify this directive and add a listener for the window resize event which does: 

`var words = [];
          $.extend(words,$scope.words);
          $elem.jQCloud('destroy');
          $elem.jQCloud('initialize');
          $elem.jQCloud('update', words);`

**Comment by mistic100** [comment]
well it works...

on the example file :
```html
  <style>
    html, body { width: 100%; height: 100% }
    #cloud { width: 50%; height: 80% }
  </style>

  <jqcloud words="words" id="cloud" colors="{{colors}}" steps="7" font-size="{from:0.09, to:0.04}" auto-resize="true"></jqcloud>
```

it's related to #9 I think

**Comment by owaaa** [comment]
In my page this did not work. I'm not sure if its related to a more complicated parent structure (it is placed inside a boostrap grid cell) under other div's which are all sized based on percentage. 

I also had issues at first even getting this to render at all. If hight was set statically, I got something to show but it was much smaller than the Div. With a non-static hight it rendered nothing. The issue was related to the word cloud being in a tab, but I've used a delay and ng-if to force a delay in the construction and it renders correct but resize still did not work. 

Anyway, I have a resize fix in my fork that listens to the resize event borrowing from a strategy I've seen in other directives. It works for me but not sure if you want to consider it as a PR. For now this is only useable for me on my fork. Otherwise great component!

**Comment by mistic100** [comment]
I updated the example

**Pull request closed without merging**
